[build]
cmd = [
  "npm install",
  "cd apps/api && npx prisma generate",
  "cd apps/api && npm run build"
]

[start]
cmd = [
  "cd apps/api && npx prisma migrate deploy",
  "cd apps/api && npm run start:prod"
]

[variables]
NODE_ENV = "production"
PORT = "3001"

[providers]
nodejs = { version = "18" }