[variables]
NODE_ENV = "production"
PORT = "3001"

[providers]
nodejs = { version = "18" }

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[build]
# Force nixpacks, ignore any Dockerfile or turbo config

[phases.install]
cmds = [
  "cd apps/api",
  "npm ci --omit=dev",
  "npm install --save-dev @nestjs/cli prisma"
]

[phases.build]
cmds = [
  "cd apps/api",
  "npx prisma generate",
  "npx nest build"
]

[phases.start]
cmd = "cd apps/api && npx prisma migrate deploy && node dist/main.js"