[variables]
NODE_ENV = "production"
PORT = "3001"

[providers]
nodejs = { version = "18" }

[phases.install]
cmds = [
  "cd apps/api",
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd apps/api",
  "npx prisma generate",
  "npx nest build"
]

[phases.start]
cmd = "cd apps/api && npx prisma migrate deploy && node dist/main.js"