[variables]
NODE_ENV = "production"
PORT = "3001"

[providers]
nodejs = { version = "18" }

[phases.install]
cmds = ["echo 'Skipping root install - using custom scripts'"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm start"