[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
cmds = [
  "cd apps/api",
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd apps/api",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "cd apps/api && npx prisma migrate deploy && node dist/main.js"
