[build]
builder = "NIXPACKS"
buildCommand = "cd apps/api && npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "cd apps/api && npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
