#!/usr/bin/env node
/**
 * Script to switch between local and production API endpoints
 * Usage: node scripts/switch-api.js [local|production]
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envLocalPath = path.join(__dirname, '..', '.env.local');

const configs = {
  local: {
    VITE_API_URL: 'http://localhost:4000',
    description: 'Local backend development'
  },
  production: {
    VITE_API_URL: 'https://api.fixia.app',
    description: 'Production API (recommended for frontend development)'
  }
};

const mode = process.argv[2];

if (!mode || !configs[mode]) {
  console.log('❌ Usage: node scripts/switch-api.js [local|production]');
  console.log('\nAvailable configurations:');
  Object.keys(configs).forEach(key => {
    console.log(`  ${key}: ${configs[key].description}`);
  });
  process.exit(1);
}

const config = configs[mode];
const envContent = `# Local Development Configuration
# Generated by switch-api.js script
# Last updated: ${new Date().toISOString()}

# API Configuration
VITE_API_URL=${config.VITE_API_URL}

# Environment
NODE_ENV=development

# Configuration: ${config.description}
`;

try {
  fs.writeFileSync(envLocalPath, envContent, 'utf8');
  console.log(`✅ Successfully switched to ${mode} configuration`);
  console.log(`📍 API URL: ${config.VITE_API_URL}`);
  console.log(`📝 Description: ${config.description}`);
  console.log('\n⚠️  Remember to restart your development server for changes to take effect!');
} catch (error) {
  console.error('❌ Error writing .env.local file:', error.message);
  process.exit(1);
}