# Railway Service Settings - CRITICAL CONFIGURATION
# This file FORCES Railway to use specific build settings

[build]
# FORCE Nixpacks - DO NOT auto-detect
builder = "nixpacks"
nixpacksConfigPath = ".nixpacks.toml"

# DISABLE auto-detection that might trigger Turbo
watchPatterns = ["apps/api/**/*"]
buildCommand = ""

[deploy]
# Production server configuration
startCommand = "cd apps/api && npx prisma migrate deploy && node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckRetries = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
# NOTE: PORT is automatically set by Railway - don't override

# Railway-specific environment
RAILWAY_SERVICE_NAME = "fixia-api"
RAILWAY_ENVIRONMENT = "production"